version: "3.1"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: user-details
      MONGO_INITDB_ROOT_USERNAME: andrzejduda
      MONGO_INITDB_ROOT_PASSWORD: andrzejduda
  mongoex:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=andrzejduda
      - ME_CONFIG_MONGODB_ADMINPASSWORD=andrzejduda
    ports:
      - "8090:8081"
    depends_on:
      - mongodb